management:
  security:
    enabled: false
  context-path: /actuator
  metrics:
    enable: true
    web:
      server:
        auto-time-requests: true
    distribution:
      sla:
        "[http.server.requests]": 5ms,100ms,200ms,300ms,500ms,1000ms
#      percentiles:
#        "[http.server.requests]": 0.05,0.5,0.95,0.99,0.99
